service: concurrency-service-api

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  stackName: concurrency-service-api
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:PutItem
      Resource: 'arn:aws:dynamodb:us-east-1:225403191552:table/streaming-table'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  apiKeys:
    - concurrency-service-api-key

functions:
  getStatus:
    handler: src/index.handler
    timeout: 30
    tracing: Active
    events:
      - http:
          path: /getStatus/{userId}
          method: get
          private: true
          documentation:
            summary: "Get concurrency status"
            pathParams:
              - name: "userId"
                description: "Given a userId, returns the concurrency status of that user."
                required: true
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "The requested concurrency status."
                responseModels:
                  "application/json": Highlight
resources:
  Resources:  
    streamingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: streaming-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE